# Running hyperparameter optimization on Chemprop model using RayTune

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/chemprop/chemprop/blob/main/examples/hpopting.ipynb)

In [1]:
# Install chemprop from GitHub if running in Google Colab
import os

if os.getenv("COLAB_RELEASE_TAG"):
    try:
        import chemprop
    except ImportError:
        !git clone https://github.com/chemprop/chemprop.git
        %cd chemprop
        !pip install ".[hpopt]"
        %cd examples

## Import packages

In [2]:
from pathlib import Path

import pandas as pd
from lightning import pytorch as pl
import ray
from ray import tune
from ray.train import CheckpointConfig, RunConfig, ScalingConfig
from ray.train.lightning import (RayDDPStrategy, RayLightningEnvironment,
                                 RayTrainReportCallback, prepare_trainer)
from ray.train.torch import TorchTrainer
from ray.tune.search.hyperopt import HyperOptSearch
from ray.tune.search.optuna import OptunaSearch
from ray.tune.schedulers import FIFOScheduler

from chemprop import data, featurizers, models, nn

/home/knathan/anaconda3/envs/chemprop/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-12-26 15:19:11,047	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
2025-12-26 15:19:11,240	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
2025-12-26 15:19:11,356	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

In [3]:
chemprop_dir = Path.cwd().parent
input_path = chemprop_dir / "tests" / "data" / "regression" / "mol" / "mol.csv" # path to your data .csv file
num_workers = 0 # number of workers for dataloader. 0 means using main process for data loading
smiles_column = 'smiles' # name of the column containing SMILES strings
target_columns = ['lipo'] # list of names of the columns containing targets

hpopt_save_dir = Path.cwd() / "hpopt" # directory to save hyperopt results
hpopt_save_dir.mkdir(exist_ok=True)

## Load data

In [4]:
df_input = pd.read_csv(input_path)
df_input

                                               smiles  lipo
0             Cn1c(CN2CCN(CC2)c3ccc(Cl)cc3)nc4ccccc14  3.54
1   COc1cc(OC)c(cc1NC(=O)CSCC(=O)O)S(=O)(=O)N2C(C)... -1.18
2              COC(=O)[C@@H](N1CCc2sccc2C1)c3ccccc3Cl  3.69
3   OC[C@H](O)CN1C(=O)C(Cc2ccccc12)NC(=O)c3cc4cc(C...  3.37
4   Cc1cccc(C[C@H](NC(=O)c2cc(nn2C)C(C)(C)C)C(=O)N...  3.10
..                                                ...   ...
95  CC(C)N(CCCNC(=O)Nc1ccc(cc1)C(C)(C)C)C[C@H]2O[C...  2.20
96  CCN(CC)CCCCNc1ncc2CN(C(=O)N(Cc3cccc(NC(=O)C=C)...  2.04
97  CCSc1c(Cc2ccccc2C(F)(F)F)sc3N(CC(C)C)C(=O)N(C)...  4.49
98                        COc1ccc(Cc2c(N)n[nH]c2N)cc1  0.20
99  CCN(CCN(C)C)S(=O)(=O)c1ccc(cc1)c2cnc(N)c(n2)C(...  2.00

[100 rows x 2 columns]

In [5]:
smis = df_input.loc[:, smiles_column].values
ys = df_input.loc[:, target_columns].values

## Make data points, splits, and datasets

In [6]:
all_data = [data.MoleculeDatapoint.from_smi(smi, y) for smi, y in zip(smis, ys)]

In [7]:
mols = [d.mol for d in all_data]  # RDkit Mol objects are use for structure based splits
train_indices, val_indices, test_indices = data.make_split_indices(mols, "random", (0.8, 0.1, 0.1))
train_data, val_data, test_data = data.split_data_by_indices(
    all_data, train_indices, val_indices, test_indices
)

The return type of make_split_indices has changed in v2.1 - see help(make_split_indices)

In [8]:
featurizer = featurizers.SimpleMoleculeMolGraphFeaturizer()

train_dset = data.MoleculeDataset(train_data[0], featurizer)
scaler = train_dset.normalize_targets()

val_dset = data.MoleculeDataset(val_data[0], featurizer)
val_dset.normalize_targets(scaler)

test_dset = data.MoleculeDataset(test_data[0], featurizer)

# Define helper function to train the model

In [9]:
def train_model(config, train_dset, val_dset, num_workers, scaler):

    # config is a dictionary containing hyperparameters used for the trial
    depth = int(config["depth"])
    ffn_hidden_dim = int(config["ffn_hidden_dim"])
    ffn_num_layers = int(config["ffn_num_layers"])
    message_hidden_dim = int(config["message_hidden_dim"])

    train_loader = data.build_dataloader(train_dset, num_workers=num_workers, shuffle=True)
    val_loader = data.build_dataloader(val_dset, num_workers=num_workers, shuffle=False)

    mp = nn.BondMessagePassing(d_h=message_hidden_dim, depth=depth)
    agg = nn.MeanAggregation()
    output_transform = nn.UnscaleTransform.from_standard_scaler(scaler)
    ffn = nn.RegressionFFN(output_transform=output_transform, input_dim=message_hidden_dim, hidden_dim=ffn_hidden_dim, n_layers=ffn_num_layers)
    batch_norm = True
    metric_list = [nn.metrics.RMSE(), nn.metrics.MAE()]
    model = models.MPNN(mp, agg, ffn, batch_norm, metric_list)

    trainer = pl.Trainer(
        accelerator="auto",
        devices=1,
        max_epochs=20, # number of epochs to train for
        # below are needed for Ray and Lightning integration
        strategy=RayDDPStrategy(),
        callbacks=[RayTrainReportCallback()],
        plugins=[RayLightningEnvironment()],
    )

    trainer = prepare_trainer(trainer)
    trainer.fit(model, train_loader, val_loader)

## Define parameter search space

In [10]:
search_space = {
    "depth": tune.qrandint(lower=2, upper=6, q=1),
    "ffn_hidden_dim": tune.qrandint(lower=300, upper=2400, q=100),
    "ffn_num_layers": tune.qrandint(lower=1, upper=3, q=1),
    "message_hidden_dim": tune.qrandint(lower=300, upper=2400, q=100),
}

In [11]:
ray.init()

scheduler = FIFOScheduler()

# Scaling config controls the resources used by Ray
scaling_config = ScalingConfig(
    num_workers=1,
    use_gpu=False, # change to True if you want to use GPU
)

# Checkpoint config controls the checkpointing behavior of Ray
checkpoint_config = CheckpointConfig(
    num_to_keep=1, # number of checkpoints to keep
    checkpoint_score_attribute="val_loss", # Save the checkpoint based on this metric
    checkpoint_score_order="min", # Save the checkpoint with the lowest metric value
)

run_config = RunConfig(
    checkpoint_config=checkpoint_config,
    storage_path=hpopt_save_dir / "ray_results", # directory to save the results
)

def train_func(config):
    trainer = TorchTrainer(
        lambda cfg: train_model(
            cfg, train_dset, val_dset, num_workers, scaler
        ),
        scaling_config=scaling_config,
        run_config=run_config,
        train_loop_config=config,
    )
    result = trainer.fit()
    tune.report(metrics=result.metrics, checkpoint=result.checkpoint)

search_alg = HyperOptSearch(
    n_initial_points=1, # number of random evaluations before tree parzen estimators
    random_state_seed=42,
)

# OptunaSearch is another search algorithm that can be used
# search_alg = OptunaSearch() 

tune_config = tune.TuneConfig(
    metric="val_loss",
    mode="min",
    num_samples=2, # number of trials to run
    scheduler=scheduler,
    search_alg=search_alg,
    trial_dirname_creator=lambda trial: str(trial.trial_id), # shorten filepaths
    
)

tuner = tune.Tuner(
    train_func,
    param_space=search_space,
    tune_config=tune_config,
)

# Start the hyperparameter search
results = tuner.fit()

(TrainController pid=22926) Attempting to start training worker group of size 1 with the following resources: [{'CPU': 1}] * 1
(RayTrainWorker pid=23102) Setting up process group for: env:// [rank=0, world_size=1]

(RayTrainWorker pid=23102) [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0

(pid=gcs_server) [2025-12-26 15:19:44,066 E 22037 22037] (gcs_server) gcs_server.cc:302: Failed to establish connection to the event+metrics exporter agent. Events and metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(TrainController pid=23216) Attempting to start training worker group of size 1 with the following resources: [{'CPU': 1}] * 1
(TrainController pid=22926) Started training worker group of size 1:
(TrainController pid=22926) - (ip=172.31.231.162, pid=23102) world_rank=0, local_rank=0, node_rank=0
(RayTrainWorker pid=23102) INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
(RayTrainWorker pid=23102) 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
(RayTrainWorker pid=23102) INFO: GPU available: False, used: False
(RayTrainWorker pid=23102) GPU available: False, used: False
(RayTrainWorker pid=23102) INFO: TPU available: False, using: 0 TPU cores
(RayTrainWorker pid=23102) TPU available: False, using: 0 TPU cores
(RayTrainWorker pid=23102) INFO: Loading `train_dataloader` to estimate number of stepping batches.
(RayTrainWorker pid=23102) Loading `train_dataloader` to estimate number of stepping batches.
(RayTrainWorker pid=23102) /home/knathan/anaconda3/envs/chemprop/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
(RayTrainWorker pid=23102) /home/knathan/anaconda3/envs/chemprop/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py:317: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
(RayTrainWorker pid=23102) /home/knathan/anaconda3/envs/chemprop/lib/python3.11/site-packages/lightning/pytorch/core/saving.py:365: Skipping 'metrics' parameter because it is not possible to safely dump to YAML.

(RayTrainWorker pid=23102) ┏━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(RayTrainWorker pid=23102) ┃   ┃ Name            ┃ Type               ┃ Params ┃ Mode  ┃ FLOPs ┃
(RayTrainWorker pid=23102) ┡━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(RayTrainWorker pid=23102) │ 0 │ message_passing │ BondMessagePassing │  579 K │ train │     0 │
(RayTrainWorker pid=23102) │ 1 │ agg             │ MeanAggregation    │      0 │ train │     0 │
(RayTrainWorker pid=23102) │ 2 │ bn              │ BatchNorm1d        │  1.0 K │ train │     0 │
(RayTrainWorker pid=23102) │ 3 │ predictor       │ RegressionFFN      │  5.0 M │ train │     0 │
(RayTrainWorker pid=23102) │ 4 │ X_d_transform   │ Identity           │      0 │ train │     0 │
(RayTrainWorker pid=23102) │ 5 │ metrics         │ ModuleList         │      0 │ train │     0 │
(RayTrainWorker pid=23102) └───┴─────────────────┴────────────────────┴────────┴───────┴───────┘
(RayTrainWorker pid=23102) Trainable params: 5.6 M
(RayTrainWorker pid=23102) Non-trainable params: 0
(RayTrainWorker pid=23102) Total params: 5.6 M
(RayTrainWorker pid=23102) Total estimated model params size (MB): 22
(RayTrainWorker pid=23102) Modules in train mode: 27
(RayTrainWorker pid=23102) Modules in eval mode: 0
(RayTrainWorker pid=23102) Total FLOPs: 0
/home/knathan/anaconda3/envs/chemprop/lib/python3.11/site-packages/lightning/pyt
(RayTrainWorker pid=23102) orch/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not
(RayTrainWorker pid=23102) have many workers which may be a bottleneck. Consider increasing the value of
(RayTrainWorker pid=23102) the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve
(RayTrainWorker pid=23102) performance.
m(RayTrainWorker pid=23102)

(raylet) [2025-12-26 15:19:45,901 E 22155 22155] (raylet) main.cc:975: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Epoch 0/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              val_loss: 0.895
Epoch 0/19 ━━━━━━━━━╺━━━━━━━━ 1/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.971
Epoch 0/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 5.83it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
Epoch 0/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 5.83it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
Epoch 0/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 5.83it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.081
Epoch 0/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 5.83it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.081
Epoch 0/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 5.83it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.081
Checkpoint successfully created at: Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-19-47.412551)
(RayTrainWorker pid=23102) Epoch 0/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 5.83it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
Reporting training result 1:                                                 1.081
(RayTrainWorker pid=23102) TrainingReport(checkpoint=Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-19-47.412551), metrics={'train_loss':
(RayTrainWorker pid=23102) 0.9927072525024414, 'train_loss_step': 1.0805681943893433, 'val/rmse':
(RayTrainWorker pid=23102) 0.925529956817627, 'val/mae': 0.7242468595504761, 'val_loss':
(RayTrainWorker pid=23102) 0.8566057085990906, 'train_loss_epoch': 0.9927072525024414, 'epoch': 0, 'step':
(RayTrainWorker pid=23102) 2}, validation_spec=None)
(RayTrainWorker pid=23102) Epoch 0/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 5.83it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.081
Epoch 1/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.081 val_loss:
(RayTrainWorker pid=23102)                                                              0.857
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Epoch 1/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.081 val_loss:
(RayTrainWorker pid=23102)                                                              0.857
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.993

(bundle_reservation_check_func pid=22217) [2025-12-26 15:19:48,038 E 22217 22333] core_worker_process.cc:825: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Epoch 1/19 ━━━━━━━━━╺━━━━━━━━ 1/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.897 val_loss:
(RayTrainWorker pid=23102)                                                              0.857
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.993
Epoch 1/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:00 • 0:00:00 4.28it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.361 val_loss:
(RayTrainWorker pid=23102)                                                              0.857
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Epoch 1/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:00 • 0:00:00 4.28it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.361 val_loss:
(RayTrainWorker pid=23102)                                                              0.857
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Epoch 1/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:00 • 0:00:00 4.28it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.361 val_loss:
(RayTrainWorker pid=23102)                                                              0.857
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.993
Epoch 1/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:00 • 0:00:00 4.28it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.361 val_loss:
(RayTrainWorker pid=23102)                                                              0.857
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.993
Epoch 1/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:00 • 0:00:00 4.28it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.361 val_loss:
(RayTrainWorker pid=23102)                                                              0.857
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.993

[2025-12-26 15:19:48,948 E 22010 22216] core_worker_process.cc:825: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(RayTrainWorker pid=23277) Setting up process group for: env:// [rank=0, world_size=1]

Checkpoint successfully created at: Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-19-50.188306)
(RayTrainWorker pid=23102) Epoch 1/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:00 • 0:00:00 4.28it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.361 val_loss:
(RayTrainWorker pid=23102)                                                              0.857
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Reporting training result 2:                         0.993
(RayTrainWorker pid=23102) TrainingReport(checkpoint=Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-19-50.188306), metrics={'train_loss':
(RayTrainWorker pid=23102) 0.789515495300293, 'train_loss_step': 0.36131206154823303, 'val/rmse':
(RayTrainWorker pid=23102) 0.9550876021385193, 'val/mae': 0.7618765234947205, 'val_loss':
(RayTrainWorker pid=23102) 0.9121923446655273, 'train_loss_epoch': 0.789515495300293, 'epoch': 1, 'step':
(RayTrainWorker pid=23102) 4}, validation_spec=None)
(RayTrainWorker pid=23102) Epoch 1/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:00 • 0:00:00 4.28it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.361 val_loss:
(RayTrainWorker pid=23102)                                                              0.857
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.993
(RayTrainWorker pid=23277) [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
Epoch 2/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.361 val_loss:
(RayTrainWorker pid=23102)                                                              0.912
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Epoch 2/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.361 val_loss:
(RayTrainWorker pid=23102)                                                              0.912
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.790
Epoch 2/19 ━━━━━━━━━╺━━━━━━━━ 1/2 0:00:02 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.223 val_loss:
(RayTrainWorker pid=23102)                                                              0.912
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.790
Epoch 2/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.04it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.307 val_loss:
(RayTrainWorker pid=23102)                                                              0.912
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Epoch 2/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.04it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.307 val_loss:
(RayTrainWorker pid=23102)                                                              0.912
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Epoch 2/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.04it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.307 val_loss:
(RayTrainWorker pid=23102)                                                              0.912
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.790
Epoch 2/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.04it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.307 val_loss:
(RayTrainWorker pid=23102)                                                              0.912
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.790
(RayTrainWorker pid=23102) Validation ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s
Epoch 2/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.04it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.307 val_loss:
(RayTrainWorker pid=23102)                                                              0.912
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.790
Checkpoint successfully created at: Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-19-55.298709)
(RayTrainWorker pid=23102) Epoch 2/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.04it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.307 val_loss:
(RayTrainWorker pid=23102)                                                              0.912
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Reporting training result 3:                         0.790
(RayTrainWorker pid=23102) TrainingReport(checkpoint=Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-19-55.298709), metrics={'train_loss':
(RayTrainWorker pid=23102) 1.2397364377975464, 'train_loss_step': 1.3065991401672363, 'val/rmse':
(RayTrainWorker pid=23102) 0.9187682867050171, 'val/mae': 0.7111909985542297, 'val_loss':
(RayTrainWorker pid=23102) 0.8441351652145386, 'train_loss_epoch': 1.2397364377975464, 'epoch': 2, 'step':
(RayTrainWorker pid=23102) 6}, validation_spec=None)
(RayTrainWorker pid=23102) Epoch 2/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.04it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.307 val_loss:
(RayTrainWorker pid=23102)                                                              0.912
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.790
Epoch 3/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.307 val_loss:
(RayTrainWorker pid=23102)                                                              0.844
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Epoch 3/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              1.307 val_loss:
(RayTrainWorker pid=23102)                                                              0.844
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              1.240
Epoch 3/19 ━━━━━━━━━╺━━━━━━━━ 1/2 0:00:01 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.889 val_loss:
(RayTrainWorker pid=23102)                                                              0.844
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              1.240

(train_func pid=22925) [2025-12-26 15:19:59,090 E 22925 22975] core_worker_process.cc:825: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14 [repeated 8x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)

Epoch 3/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.29it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.760 val_loss:
(RayTrainWorker pid=23102)                                                              0.844
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              1.240
Epoch 3/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.29it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.760 val_loss:
(RayTrainWorker pid=23102)                                                              0.844
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Epoch 3/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.29it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.760 val_loss:
(RayTrainWorker pid=23102)                                                              0.844
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              1.240
Epoch 3/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.29it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.760 val_loss:
(RayTrainWorker pid=23102)                                                              0.844
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              1.240
(RayTrainWorker pid=23102) Validation ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s
Epoch 3/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.29it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.760 val_loss:
(RayTrainWorker pid=23102)                                                              0.844
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              1.240
Checkpoint successfully created at: Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-20-00.548113)
(RayTrainWorker pid=23102) Epoch 3/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.29it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.760 val_loss:
(RayTrainWorker pid=23102)                                                              0.844
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Reporting training result 4:                         1.240
(RayTrainWorker pid=23102) TrainingReport(checkpoint=Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-20-00.548113), metrics={'train_loss':
(RayTrainWorker pid=23102) 0.8630542755126953, 'train_loss_step': 0.7599794268608093, 'val/rmse':
(RayTrainWorker pid=23102) 0.960074782371521, 'val/mae': 0.7631434798240662, 'val_loss':
(RayTrainWorker pid=23102) 0.9217435717582703, 'train_loss_epoch': 0.8630542755126953, 'epoch': 3, 'step':
(RayTrainWorker pid=23102) 8}, validation_spec=None)
(RayTrainWorker pid=23102) Epoch 3/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.29it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.760 val_loss:
(RayTrainWorker pid=23102)                                                              0.844
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              1.240
Epoch 4/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.760 val_loss:
(RayTrainWorker pid=23102)                                                              0.922
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Epoch 4/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.760 val_loss:
(RayTrainWorker pid=23102)                                                              0.922
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.863
Epoch 4/19 ━━━━━━━━━╺━━━━━━━━ 1/2 0:00:01 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.848 val_loss:
(RayTrainWorker pid=23102)                                                              0.922
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.863
Epoch 4/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.74it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.502 val_loss:
(RayTrainWorker pid=23102)                                                              0.922
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Epoch 4/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.74it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.502 val_loss:
(RayTrainWorker pid=23102)                                                              0.922
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Epoch 4/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.74it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.502 val_loss:
(RayTrainWorker pid=23102)                                                              0.922
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.863
Epoch 4/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.74it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.502 val_loss:
(RayTrainWorker pid=23102)                                                              0.922
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.863
(RayTrainWorker pid=23102) Validation ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s
Epoch 4/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.74it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.502 val_loss:
(RayTrainWorker pid=23102)                                                              0.922
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.863

(SynchronizationActor pid=23101) [2025-12-26 15:20:05,963 E 23101 23145] core_worker_process.cc:825: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14 [repeated 3x across cluster]

Checkpoint successfully created at: Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-20-07.061505)
(RayTrainWorker pid=23102) Epoch 4/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.74it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.502 val_loss:
(RayTrainWorker pid=23102)                                                              0.922
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Reporting training result 5:                         0.863
(RayTrainWorker pid=23102) TrainingReport(checkpoint=Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-20-07.061505), metrics={'train_loss':
(RayTrainWorker pid=23102) 0.7789014577865601, 'train_loss_step': 0.5021898746490479, 'val/rmse':
(RayTrainWorker pid=23102) 0.9553437829017639, 'val/mae': 0.7726725339889526, 'val_loss':
(RayTrainWorker pid=23102) 0.9126817584037781, 'train_loss_epoch': 0.7789014577865601, 'epoch': 4, 'step':
(RayTrainWorker pid=23102) 10}, validation_spec=None)
(RayTrainWorker pid=23102) Epoch 4/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.74it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.502 val_loss:
(RayTrainWorker pid=23102)                                                              0.922
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.863

(TrainController pid=23216) Started training worker group of size 1:
(TrainController pid=23216) - (ip=172.31.231.162, pid=23277) world_rank=0, local_rank=0, node_rank=0

Epoch 5/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.502 val_loss:
(RayTrainWorker pid=23102)                                                              0.913
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Epoch 5/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.502 val_loss:
(RayTrainWorker pid=23102)                                                              0.913
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.779

(RayTrainWorker pid=23277) INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
(RayTrainWorker pid=23277) 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
(RayTrainWorker pid=23277) INFO: GPU available: False, used: False
(RayTrainWorker pid=23277) GPU available: False, used: False
(RayTrainWorker pid=23277) INFO: TPU available: False, using: 0 TPU cores
(RayTrainWorker pid=23277) TPU available: False, using: 0 TPU cores
(RayTrainWorker pid=23277) INFO: Loading `train_dataloader` to estimate number of stepping batches.
(RayTrainWorker pid=23277) Loading `train_dataloader` to estimate number of stepping batches.
(RayTrainWorker pid=23277) /home/knathan/anaconda3/envs/chemprop/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
(RayTrainWorker pid=23277) /home/knathan/anaconda3/envs/chemprop/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py:317: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
(RayTrainWorker pid=23277) /home/knathan/anaconda3/envs/chemprop/lib/python3.11/site-packages/lightning/pytorch/core/saving.py:365: Skipping 'metrics' parameter because it is not possible to safely dump to YAML.

(RayTrainWorker pid=23277) ┏━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(RayTrainWorker pid=23277) ┃   ┃ Name            ┃ Type               ┃ Params ┃ Mode  ┃ FLOPs ┃
(RayTrainWorker pid=23277) ┡━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(RayTrainWorker pid=23277) │ 0 │ message_passing │ BondMessagePassing │  383 K │ train │     0 │
(RayTrainWorker pid=23277) │ 1 │ agg             │ MeanAggregation    │      0 │ train │     0 │
(RayTrainWorker pid=23277) │ 2 │ bn              │ BatchNorm1d        │    800 │ train │     0 │
(RayTrainWorker pid=23277) │ 3 │ predictor       │ RegressionFFN      │  5.7 M │ train │     0 │
(RayTrainWorker pid=23277) │ 4 │ X_d_transform   │ Identity           │      0 │ train │     0 │
(RayTrainWorker pid=23277) │ 5 │ metrics         │ ModuleList         │      0 │ train │     0 │
(RayTrainWorker pid=23277) └───┴─────────────────┴────────────────────┴────────┴───────┴───────┘
(RayTrainWorker pid=23277) Trainable params: 6.1 M
(RayTrainWorker pid=23277) Non-trainable params: 0
(RayTrainWorker pid=23277) Total params: 6.1 M
(RayTrainWorker pid=23277) Total estimated model params size (MB): 24
(RayTrainWorker pid=23277) Modules in train mode: 27
(RayTrainWorker pid=23277) Modules in eval mode: 0
(RayTrainWorker pid=23277) Total FLOPs: 0
/home/knathan/anaconda3/envs/chemprop/lib/python3.11/site-packages/lightning/pyt
(RayTrainWorker pid=23277) orch/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not
(RayTrainWorker pid=23277) have many workers which may be a bottleneck. Consider increasing the value of
(RayTrainWorker pid=23277) the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve
(RayTrainWorker pid=23277) performance.
m(RayTrainWorker pid=23277)
Epoch 5/19 ━━━━━━━━━╺━━━━━━━━ 1/2 0:00:01 • -:--:-- 0.00it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.584 val_loss:
(RayTrainWorker pid=23102)                                                              0.913
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.779
Epoch 5/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.17it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.973 val_loss:
(RayTrainWorker pid=23102)                                                              0.913
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.779
Epoch 5/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.17it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.973 val_loss:
(RayTrainWorker pid=23102)                                                              0.913
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.779
Epoch 5/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.17it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.973 val_loss:
(RayTrainWorker pid=23102)                                                              0.913
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.779
Epoch 5/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.17it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.973 val_loss:
(RayTrainWorker pid=23102)                                                              0.913
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.779
(RayTrainWorker pid=23102) Validation ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s
Epoch 0/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 1.000
(RayTrainWorker pid=23277)                                                              val_loss: 0.884
Epoch 5/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.17it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.973 val_loss:
(RayTrainWorker pid=23102)                                                              0.913
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.779

(TrainController pid=23216) [2025-12-26 15:20:11,373 E 23216 23255] core_worker_process.cc:825: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14 [repeated 2x across cluster]

Checkpoint successfully created at: Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-20-13.450014)
(RayTrainWorker pid=23102) Epoch 5/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.17it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.973 val_loss:
(RayTrainWorker pid=23102)                                                              0.913
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
Reporting training result 6:                         0.779
(RayTrainWorker pid=23102) TrainingReport(checkpoint=Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-20-13.450014), metrics={'train_loss':
(RayTrainWorker pid=23102) 0.6615119576454163, 'train_loss_step': 0.9733167290687561, 'val/rmse':
(RayTrainWorker pid=23102) 0.9415909051895142, 'val/mae': 0.7538264393806458, 'val_loss':
(RayTrainWorker pid=23102) 0.8865934610366821, 'train_loss_epoch': 0.6615119576454163, 'epoch': 5, 'step':
(RayTrainWorker pid=23102) 12}, validation_spec=None)
(RayTrainWorker pid=23102) Epoch 5/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 2.17it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.973 val_loss:
(RayTrainWorker pid=23102)                                                              0.913
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.779
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.979
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              1.021
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              1.021
(RayTrainWorker pid=23277) Validation ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              1.021
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.973 val_loss:
(RayTrainWorker pid=23102)                                                              0.887
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.973 val_loss:
(RayTrainWorker pid=23102)                                                              0.887
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.662
Epoch 6/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000        [repeated 8x across cluster]
Checkpoint successfully created at: Checkpoint(filesystem=local,
(RayTrainWorker pid=23277) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23277) 15-19-18/checkpoint_2025-12-26_15-20-16.266874)
(RayTrainWorker pid=23277) Epoch 0/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:04 • 0:00:00 4.58it/s v_num: 1.000
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              1.021
Reporting training result 1:
(RayTrainWorker pid=23277) TrainingReport(checkpoint=Checkpoint(filesystem=local,
(RayTrainWorker pid=23277) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23277) 15-19-18/checkpoint_2025-12-26_15-20-16.266874), metrics={'train_loss':
(RayTrainWorker pid=23277) 0.9872263073921204, 'train_loss_step': 1.0210890769958496, 'val/rmse':
(RayTrainWorker pid=23277) 0.93086838722229, 'val/mae': 0.7359216213226318, 'val_loss': 0.8665159940719604,
(RayTrainWorker pid=23277) 'train_loss_epoch': 0.9872263073921204, 'epoch': 0, 'step': 2},
(RayTrainWorker pid=23277) validation_spec=None)
(RayTrainWorker pid=23277) Epoch 0/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:04 • 0:00:00 4.58it/s v_num: 1.000
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              1.021
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.466 val_loss:
(RayTrainWorker pid=23102)                                                              0.887
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.662
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.563 val_loss:
(RayTrainWorker pid=23102)                                                              0.887
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.563 val_loss:
(RayTrainWorker pid=23102)                                                              0.887
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.563 val_loss:
(RayTrainWorker pid=23102)                                                              0.887
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.662
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.867
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.867
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              0.987
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.887
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.662
Epoch 6/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.35it/s v_num: 0.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.887
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.662
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.867
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              0.987
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.867
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              0.987
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.867
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.867
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.867
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              0.987
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.867
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              0.987
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-20-19.638868)
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.887
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.887
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.662
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.884
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.884
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.486
Epoch 7/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 0.000        [repeated 14x across cluster]
Checkpoint successfully created at: Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) Epoch 6/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.35it/s v_num: 0.000        [repeated 2x across cluster]
Reporting training result 7:                         0.662
(RayTrainWorker pid=23102) TrainingReport(checkpoint=Checkpoint(filesystem=local,
(RayTrainWorker pid=23102) 15-19-18/checkpoint_2025-12-26_15-20-19.638868), metrics={'train_loss':
(RayTrainWorker pid=23102) 0.4856085181236267, 'train_loss_step': 0.5625557899475098, 'val/rmse':
(RayTrainWorker pid=23102) 0.9404134750366211, 'val/mae': 0.7421301603317261, 'val_loss':
(RayTrainWorker pid=23102) 0.8843774795532227, 'train_loss_epoch': 0.4856085181236267, 'epoch': 6, 'step':
(RayTrainWorker pid=23102) 14}, validation_spec=None)
Checkpoint successfully created at: Checkpoint(filesystem=local,
(RayTrainWorker pid=23277) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23277) 15-19-18/checkpoint_2025-12-26_15-20-21.224658)
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.867
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
Reporting training result 2:                         0.987
(RayTrainWorker pid=23277) TrainingReport(checkpoint=Checkpoint(filesystem=local,
(RayTrainWorker pid=23277) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23277) 15-19-18/checkpoint_2025-12-26_15-20-21.224658), metrics={'train_loss':
(RayTrainWorker pid=23277) 1.0009845495224, 'train_loss_step': 0.6578197479248047, 'val/rmse':
(RayTrainWorker pid=23277) 0.9483866691589355, 'val/mae': 0.7480173707008362, 'val_loss':
(RayTrainWorker pid=23277) 0.8994373083114624, 'train_loss_epoch': 1.0009845495224, 'epoch': 1, 'step': 4},
(RayTrainWorker pid=23277) validation_spec=None)
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.867
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              0.987
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.899
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              1.001
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.899
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              1.001
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.884
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.486
(RayTrainWorker pid=23102)                                                              0.357 val_loss:     [repeated 19x across cluster]
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.899
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              1.001
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.884
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.486
Epoch 1/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 6.46it/s v_num: 1.000
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.884
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.884
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.486
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.899
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.899
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              train_loss_step:
(RayTrainWorker pid=23277)                                                              0.899
(RayTrainWorker pid=23277)                                                              train_loss_epoch:
(RayTrainWorker pid=23277)                                                              1.001
(RayTrainWorker pid=23102)                                                              train_loss_step:
(RayTrainWorker pid=23102)                                                              0.884
(RayTrainWorker pid=23102)                                                              train_loss_epoch:
(RayTrainWorker pid=23102)                                                              0.486
Epoch 7/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 3.49it/s v_num: 0.000

(RayTrainWorker pid=23102) INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
(RayTrainWorker pid=23277) [2025-12-26 15:20:15,832 E 23277 23363] core_worker_process.cc:825: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14 [repeated 2x across cluster]

`Trainer.fit` stopped: `max_epochs=20` reached.
(RayTrainWorker pid=23102)                                                               train_loss_step:
(RayTrainWorker pid=23102)                                                               0.760
(RayTrainWorker pid=23102)                                                               train_loss_epoch:
(RayTrainWorker pid=23102)                                                               0.102
(RayTrainWorker pid=23102)                                                               train_loss_step:
(RayTrainWorker pid=23102)                                                               0.723
(RayTrainWorker pid=23102)                                                               train_loss_epoch:
(RayTrainWorker pid=23102)                                                               0.104
(RayTrainWorker pid=23102)
(RayTrainWorker pid=23102) 'train_loss_epoch': 0.1022099107503891, 'epoch': 18, 'step': 38},
(RayTrainWorker pid=23102) validation_spec=None)
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.844
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.100
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.844
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.100
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.844
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.844
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.100
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.844
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.100
(RayTrainWorker pid=23277) Validation  ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.844
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.100
(RayTrainWorker pid=23277) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23277) 15-19-18/checkpoint_2025-12-26_15-21-08.223313)
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.844
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.844
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.100
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.838
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.838
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.081
Epoch 17/19 ━━━━━━━━━━━━━━━━━━ 0/2 0:00:00 • -:--:-- 0.00it/s v_num: 1.000       [repeated 20x across cluster]
(RayTrainWorker pid=23277) Epoch 16/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 1.33it/s v_num: 1.000       [repeated 7x across cluster]

(train_func pid=22851) /home/knathan/anaconda3/envs/chemprop/lib/python3.11/site-packages/ray/tune/trainable/trainable_fn_utils.py:41: RayDeprecationWarning: The `Checkpoint` class should be imported from `ray.tune` when passing it to `ray.tune.report` in a Tune function. Please update your imports. See this issue for more context and migration options: https://github.com/ray-project/ray/issues/49454. Disable these warnings by setting the environment variable: RAY_TRAIN_ENABLE_V2_MIGRATION_WARNINGS=0
(train_func pid=22851)   _log_deprecation_warning(
(train_func pid=22851) Checkpoint successfully created at: Checkpoint(filesystem=local, path=/home/knathan/ray_results/train_func_2025-12-26_15-19-18/f465f543/checkpoint_000000)

(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.838
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.081
Checkpoint successfully created at: Checkpoint(filesystem=local,  [repeated 3x across cluster]
Reporting training result 17:  [repeated 3x across cluster]
(RayTrainWorker pid=23277) TrainingReport(checkpoint=Checkpoint(filesystem=local,  [repeated 3x across cluster]
(RayTrainWorker pid=23277) 15-19-18/checkpoint_2025-12-26_15-21-08.223313), metrics={'train_loss':  [repeated 3x across cluster]
(RayTrainWorker pid=23277) 0.08066482841968536, 'train_loss_step': 0.05540667846798897, 'val/rmse':  [repeated 3x across cluster]
(RayTrainWorker pid=23277) 0.9155011177062988, 'val/mae': 0.7267448902130127, 'val_loss':  [repeated 3x across cluster]
(RayTrainWorker pid=23277)                                                               0.074 val_loss:    [repeated 24x across cluster]
Epoch 19/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:02 • 0:00:00 1.21it/s v_num: 0.000
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.838
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.081
(RayTrainWorker pid=23277) 0.8381422758102417, 'train_loss_epoch': 0.08066482841968536, 'epoch': 16,  [repeated 2x across cluster]
(RayTrainWorker pid=23277) 'step': 34}, validation_spec=None) [repeated 2x across cluster]
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.838
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.838
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.081
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.838
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.081
Epoch 17/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 2.65it/s v_num: 1.000
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.838
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.081
(RayTrainWorker pid=23277) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23277) 15-19-18/checkpoint_2025-12-26_15-21-10.781498)
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.838
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.838
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.081
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.828
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.828
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.083
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.828
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.083
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.828
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.083
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.828
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.828
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.083
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.828
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.083
Epoch 18/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 4.39it/s v_num: 1.000
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.828
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.083
(RayTrainWorker pid=23277) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23277) 15-19-18/checkpoint_2025-12-26_15-21-13.246924)
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.828
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.828
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.083
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.815
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.815
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.072
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.815
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.072
Epoch 19/19 ━━━━━━━━━╺━━━━━━━━ 1/2 0:00:00 • -:--:-- 0.00it/s v_num: 1.000       [repeated 15x across cluster]
(RayTrainWorker pid=23277) Epoch 18/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:01 • 0:00:00 4.39it/s v_num: 1.000       [repeated 4x across cluster]
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.815
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.815
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.815
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.072
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.815
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.072
Epoch 19/19 ━━━━━━━━━━━━━━━━━━ 2/2 0:00:00 • 0:00:00 5.07it/s v_num: 1.000
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.815
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.072
(RayTrainWorker pid=23277) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23277) 15-19-18/checkpoint_2025-12-26_15-21-15.015442)
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.815
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277) path=/home/knathan/chemprop/examples/hpopt/ray_results/ray_train_run-2025-12-26_
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.815
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.072
Checkpoint successfully created at: Checkpoint(filesystem=local,  [repeated 3x across cluster]
Reporting training result 20:  [repeated 3x across cluster]
(RayTrainWorker pid=23277) TrainingReport(checkpoint=Checkpoint(filesystem=local,  [repeated 3x across cluster]
(RayTrainWorker pid=23277) 15-19-18/checkpoint_2025-12-26_15-21-15.015442), metrics={'train_loss':  [repeated 3x across cluster]
(RayTrainWorker pid=23277) 0.06967304646968842, 'train_loss_step': 0.12719179689884186, 'val/rmse':  [repeated 3x across cluster]
(RayTrainWorker pid=23277) 0.8947698473930359, 'val/mae': 0.7140004634857178, 'val_loss':  [repeated 3x across cluster]
(RayTrainWorker pid=23277)                                                               0.127 val_loss:    [repeated 27x across cluster]

(RayTrainWorker pid=23277) INFO: `Trainer.fit` stopped: `max_epochs=20` reached.

`Trainer.fit` stopped: `max_epochs=20` reached.
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.815
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               train_loss_step:
(RayTrainWorker pid=23277)                                                               0.801
(RayTrainWorker pid=23277)                                                               train_loss_epoch:
(RayTrainWorker pid=23277)                                                               0.070
(RayTrainWorker pid=23277)
(RayTrainWorker pid=23277) 0.8006130456924438, 'train_loss_epoch': 0.06967304646968842, 'epoch': 19,  [repeated 3x across cluster]
(RayTrainWorker pid=23277) 'step': 40}, validation_spec=None) [repeated 3x across cluster]

(train_func pid=22925) /home/knathan/anaconda3/envs/chemprop/lib/python3.11/site-packages/ray/tune/trainable/trainable_fn_utils.py:41: RayDeprecationWarning: The `Checkpoint` class should be imported from `ray.tune` when passing it to `ray.tune.report` in a Tune function. Please update your imports. See this issue for more context and migration options: https://github.com/ray-project/ray/issues/49454. Disable these warnings by setting the environment variable: RAY_TRAIN_ENABLE_V2_MIGRATION_WARNINGS=0
(train_func pid=22925)   _log_deprecation_warning(
2025-12-26 15:21:18,674	INFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to '/home/knathan/ray_results/train_func_2025-12-26_15-19-18' in 0.0075s.
2025-12-26 15:21:18,684	INFO tune.py:1041 -- Total run time: 119.69 seconds (119.58 seconds for the tuning loop).

(train_func pid=22925) Checkpoint successfully created at: Checkpoint(filesystem=local, path=/home/knathan/ray_results/train_func_2025-12-26_15-19-18/fd19e1ec/checkpoint_000000)

## Hyperparameter optimization results

In [12]:
results

ResultGrid<[
  Result(
    metrics={'train_loss': 0.10441400855779648, 'train_loss_step': 0.1630178987979889, 'val/rmse': 0.8502783179283142, 'val/mae': 0.6861981153488159, 'val_loss': 0.7229731678962708, 'train_loss_epoch': 0.10441400855779648, 'epoch': 19, 'step': 40},
    path='/home/knathan/ray_results/train_func_2025-12-26_15-19-18/f465f543',
    filesystem='local',
    checkpoint=Checkpoint(filesystem=local, path=/home/knathan/ray_results/train_func_2025-12-26_15-19-18/f465f543/checkpoint_000000)
  ),
  Result(
    metrics={'train_loss': 0.06967304646968842, 'train_loss_step': 0.12719179689884186, 'val/rmse': 0.8947698473930359, 'val/mae': 0.7140004634857178, 'val_loss': 0.8006130456924438, 'train_loss_epoch': 0.06967304646968842, 'epoch': 19, 'step': 40},
    path='/home/knathan/ray_results/train_func_2025-12-26_15-19-18/fd19e1ec',
    filesystem='local',
    checkpoint=Checkpoint(filesystem=local, path=/home/knathan/ray_results/train_func_2025-12-26_15-19-18/fd19e1ec/checkpoint_000000)
  )
]>

In [13]:
# results of all trials
result_df = results.get_dataframe()
result_df

,train_loss,train_loss_step,val/rmse,val/mae,val_loss,train_loss_epoch,epoch,step,timestamp,checkpoint_dir_name,...,pid,hostname,node_ip,time_since_restore,iterations_since_restore,config/depth,config/ffn_hidden_dim,config/ffn_num_layers,config/message_hidden_dim,logdir
0,0.104414,0.163018,0.850278,0.686198,0.722973,0.104414,19,40,1766787669,checkpoint_000000,...,22851,Knathan-Laptop,172.31.231.162,101.408826,1,2,2000,2,500,f465f543
1,0.069673,0.127192,0.894770,0.714000,0.800613,0.069673,19,40,1766787678,checkpoint_000000,...,22925,Knathan-Laptop,172.31.231.162,98.953282,1,2,2200,2,400,fd19e1ec

In [14]:
# best configuration
best_result = results.get_best_result()
best_config = best_result.config
best_config

{'depth': 2,
 'ffn_hidden_dim': 2000,
 'ffn_num_layers': 2,
 'message_hidden_dim': 500}

In [15]:
# best model checkpoint path
best_result = results.get_best_result()
best_checkpoint_path = Path(best_result.checkpoint.path) / "checkpoint.ckpt"
print(f"Best model checkpoint path: {best_checkpoint_path}")

Best model checkpoint path: /home/knathan/ray_results/train_func_2025-12-26_15-19-18/f465f543/checkpoint_000000/checkpoint.ckpt

In [16]:
ray.shutdown()